version: '3.9'
services:
  mysql:
    build:
      context: ./mysql
    container_name: custom-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phonedb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    build:
      context: ./phpmyAdmin  
    container_name: phpmyadmin-container
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql 
      PMA_USER: myuser
      PMA_PASSWORD: password
    ports:
      - "8080:80"
  
  flask-app:
    build:
      context: ./interface_web
    container_name: flask-app
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    volumes:
    - ./interface_web:/a

  

